### ISSUE TITLE
Filtering drop down menus are confusing

### ISSUE THREAD

**Issue by jaflynn5** [debugpoint136/virus-browser#13]
Instead of blank boxes, could the filtering drop down menu default say something like "No Filter Applied"?
![image](https://user-images.githubusercontent.com/13970427/82762657-dcff6800-9dc7-11ea-869e-4d0b71afe1df.png)
That way, if a user wants to remove the filter for that column, it is more intuitive than selecting the blank space:
![image](https://user-images.githubusercontent.com/13970427/82762663-eab4ed80-9dc7-11ea-9123-dc6a2447b6a3.png)

**Comment by debugpoint136** [comment]
Fixed in new Data table
