### ISSUE TITLE
"Country" metadata is not standardized

### ISSUE THREAD

**Issue by jaflynn5** [debugpoint136/virus-browser#14]
Country metadata that is "USA" is displayed as a different color than "USA: Nashville, TN"
![image](https://user-images.githubusercontent.com/13970427/82762692-0c15d980-9dc8-11ea-9d1b-f80f39504be1.png)
![image](https://user-images.githubusercontent.com/13970427/82762693-0f10ca00-9dc8-11ea-9451-f6fc9fdf201a.png)

**Comment by debugpoint136** [comment]
Assigning to @lidaof @fanc-WU

**Comment by fanc-WU** [comment]
After upgrading to metadata_v3, country is no longer a metadata term. new metadata term "location" is standardized to continent and country. both on datatable and public data hub.
