### ISSUE TITLE
Duplicate options in table drop down menus

### ISSUE THREAD

**Issue by jaflynn5** [debugpoint136/virus-browser#16]
"C" is listed twice in the options for sorting isolates (in MERS):
![image](https://user-images.githubusercontent.com/13970427/82762728-4d0dee00-9dc8-11ea-8297-30a3d5612f57.png)

"B", "C", and "R" are listed twice for sorting isolates (in SARS), and the sort options are not in alphabetical order:
![image](https://user-images.githubusercontent.com/13970427/82762752-644cdb80-9dc8-11ea-9cf1-967fac5b7e86.png)

**Comment by debugpoint136** [comment]
Resolved by updated data table.
