### ISSUE TITLE
Bugs and changes

### ISSUE THREAD

**Issue by gavrielm** [debugpoint136/virus-browser#3]
### Landing page

- Featured Datahubs dropdown menu gets cut off

### Data table

- Add the ability to search for specific accession/country/collection date

    
### Tree view

- For accessions on the right-half of the tree, the metadata display windows get cut off from view

- Accessions selected in data table should also be color-coded in the tree

- "Democratic Republic of the Congo" gets cutoff

- Would be useful to have a continent category

    
### Browser view

- Gene annotations track -> Ensembl links are not useful

- SNV track -> Hovering over SNVs with mouse does not bring up display window, need to click on SNV. This is different than other tracks.

- Public data hubs -> If I first add a Diagnostics data hub or a Recombination events hub, I can't add any of the immune epitopes data hubs nor the RNA modifications data hub. Seems that the problem is that these latter hubs are not set to be loaded automatically

- "Help" dropdown menu -> Documentation -> documentation for the Wash U epigenome browser but not for the Wash U virus genome browser

- Minimize the size of the left-hand side bar so that the browser view is enlarged. Try left-aligning the "Wash U Virus Genome Browser" at the top. Also try removing "Choose a" from the "Choose a Virus Reference". Then remove whitespace. Also add a little more whitespace between the virus reference dropdown menu and the edge of the page.

  
### Documentation

- Not up-to-date. Is it feasible to replace with the supplementary notes of the manuscript?

**Comment by debugpoint136** [comment]
- **Add the ability to search for specific accession/country/collection date** -  Feature added. Please test and provide feedback @gavrielm

**Comment by debugpoint136** [comment]
Assigning to @debugpoint136 

- For accessions on the right-half of the tree, the metadata display windows get cut off from view

- Accessions selected in data table should also be color-coded in the tree

- "Democratic Republic of the Congo" gets cutoff

- Would be useful to have a continent category

**Comment by debugpoint136** [comment]
@gavrielm if you don't mind, could you please revisit and split the remaining tasks as individual items - it's easier to assign and track. Thanks!
