### ISSUE TITLE
Clade on the treeview is not matching the datatable.

### ISSUE THREAD

**Issue by fanc-WU** [debugpoint136/virus-browser#45]
The one on datatable
![image](https://user-images.githubusercontent.com/57769184/87719502-12e21c80-c779-11ea-8d27-344578570691.png)
The one on treeview:
![image](https://user-images.githubusercontent.com/57769184/87719578-2db49100-c779-11ea-8e3f-89e12633e5c7.png)

**Comment by debugpoint136** [comment]
Should be fixed. Test and confirm

**Comment by debugpoint136** [comment]
<img width="904" alt="Screen Shot 2020-07-21 at 10 08 21 AM" src="https://user-images.githubusercontent.com/2250674/88072321-8352ba00-cb3a-11ea-8296-7bc0c848ed1b.png">

**Comment by fanc-WU** [comment]
confirm: The clades are matching.

**Comment by fanc-WU** [comment]
However, the tree has multiple "empty" points (the gray ones). It might not be updating (It seems to me that the shape of the tree hasn't changed since the first update). The tree is at /bar/cfan/nextstrain/latest/strain_updated.fa.tree.
Please check
Thank you so much

**Comment by fanc-WU** [comment]
confirm: tree fixed.
