### ISSUE TITLE
Spacing between bars and labels in gene annotations track

### ISSUE THREAD

**Issue by gavrielm** [debugpoint136/virus-browser#47]
Can the spacing between the bars and labels in the gene annotations track be increased (top part of attached screenshot)? Can the spacing be the same as shown for the bars and labels in the TRS track (bottom part of attached screenshot)?

<img width="2124" alt="Screen Shot 2020-08-10 at 10 16 41 AM" src="https://user-images.githubusercontent.com/8413053/89799668-6551f700-daf3-11ea-9230-43e1935efbc0.png">

**Comment by lidaof** [comment]
sure, changed and will be effect when will push the update.
