### ISSUE TITLE
Data table ID numbers do not show last 

### ISSUE THREAD

**Issue by jaflynn5** [debugpoint136/virus-browser#5]
The last number in the data table range is not displayed. For example, in the attached picture, ID 220 is not shown. 

One solution may just be to get rid of the IDs since they do not provide the user any real information. The text box could still display ranges.

![image](https://user-images.githubusercontent.com/13970427/82762394-62821880-9dc6-11ea-8a39-e02d282ae770.png)

**Comment by debugpoint136** [comment]
Resolved as part of new data table
