### ISSUE TITLE
unable to load data in data table view

### ISSUE THREAD

**Issue by pbostyn** [debugpoint136/virus-browser#54]
I am just starting to explore the virus genome browser. I seem to be unable to load any data in the data table view. 
![image](https://user-images.githubusercontent.com/72874454/96008676-181a3a80-0e40-11eb-829a-0abfff492827.png)

**Comment by debugpoint136** [comment]
I am looking into it, seems like the data provider service is down. I will get back in a bit, sorry about that.

**Comment by debugpoint136** [comment]
The service is back online. You should be able to see the data table view now. Please let me know if you have any issues.
