### ISSUE TITLE
Could filtering could be dynamically updated

### ISSUE THREAD

**Issue by jaflynn5** [debugpoint136/virus-browser#6]
After filtering strains by one column in the data table (for example, "ID: 200 to 220"), most accession letters that you can sort by do not reveal any strains (in Ebola, when you do this, there are only accessions that start with "K" in this range). However, the user still has the option to select "A", "B", ect., which do not load any data into view. Should these options be dynamically removed if there are no strains available given the prior filtering steps?

**Comment by debugpoint136** [comment]
Resolved as part of new data table
